### ISSUE TITLE
override meeting id manually

### ISSUE THREAD

**Issue by a-kempka** [jrchamp/moodle-mod_zoom#598] opened 2024-06-14 13:23 UTC
As an administrator I would like to define or override the meeting ID of a meeting set up by mod_zoom. Upon cloning a course with a mod_zoom activity I should be able to configure if a new meeting is created for each cloned course or if the meeting should stay the same.

One use case is to create clones of a course so that each course has the same meeting (id, and code) that can be reused.

**Comment by jrchamp** [comment] 2024-06-20 16:02
Hi @a-kempka,

While we understand the potential benefits of having the same meeting link in multiple Moodle courses, the functionality difference between adding the Zoom meeting's join link URL and using the Zoom activity is minimal for multi-course situations. In contrast, the security concerns of allowing either instructors or administrators to arbitrarily grant access to any meeting within the Zoom environment is not something that we are comfortable with. When we determined which Granular OAuth scopes were needed for this plugin, we specifically excluded the scopes that would have allowed us to list all meetings for all users. This allows us to avoid automatically interacting with meetings that were not created by this plugin. Allowing manual editing in the interface would largely negate this security measure.

As an alternative to using a bare URL, a common course that contains shared meetings could be used. If you have other ideas that will preserve the privacy of non-Moodle Zoom meetings, we would be interested to know more.

Closing as duplicate of #518.

**Closed as not planned by jrchamp** 2024-06-20 16:02 UTC
Labels: not a bug
