### ISSUE TITLE
Existing Meeting in Zoom

### ISSUE THREAD

**Issue by learning101010** [jrchamp/moodle-mod_zoom#609] opened 2024-07-31 00:59 UTC
Hello everyone,

Great Plugin, 
Question only 
It is possible to use the existing zoom meeting instead of creating new one ?

**Comment by jrchamp** [comment] 2024-07-31 21:36
Hi @learning101010,

No, the plugin does not allow you to use an existing meeting.

Marking this as somewhat a duplicate of #519

**Closed as not planned** 2024-07-31 21:37 UTC
Labels: not a bug
