### ISSUE TITLE
Edit menu of Zoom activities gets overlaid by following course content

### ISSUE THREAD

**Issue by mwreichel** [jrchamp/moodle-mod_zoom#532] opened 2023-10-24 15:00 UTC
Hi,
our teachers reported a bug which appears in Moodle 4.2 (as well as 4.1), using the Zoom activity:

In editing mode - when you click on the three dots to open the editing menu of a Zoom activity - the menu is overlaid by some following activites or ressources in the same section. (When the Zoom activity is the last one in a section, this doesn't matter.)
Using the mouse cursor, the menu is flickering and you can't choose an option of the menu. Using the keyboard, this doesn't happen.

This happens with different themes, at least with "boost".

[zoom_screencast.webm](https://github.com/ncstate-delta/moodle-mod_zoom/assets/16242126/923eb76d-7c55-4e6d-8b86-8f44d2864802)

We would appreciate a fix for that.

Thanks,
Martin

**Comment by jrchamp** [comment] 2023-10-24 15:57
I believe this may be a duplicate of #533. When I excluded the ".zoom:hover" rule from the CSS, the three dots menu stopped flickering. Please let me know if that resolves the issue.

**Comment by mwreichel** [comment] 2023-10-24 16:02
Hi,
thanks for your fast answer and the further hint. I will test it tomorrow and let you know afterwards.

**Comment by mwreichel** [comment] 2023-10-25 09:05
@jrchamp : I already tested the behaviour again and this behaviour is related with the other one.
Thanks again!

**Closed as completed** 2023-10-25 09:21 UTC
Labels: more information needed

**Comment by bernhard-wunderbyte** [comment] 2023-10-31 14:12
We fixed this in Wunderbyte Table 1.8.0: https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/releases/tag/v1.8.0

**Comment by jrchamp** [comment] 2023-10-31 16:46
Thanks @bernhard-wunderbyte and @mwreichel! Now everyone will benefit. 😁

**Comment by bernhard-wunderbyte** [comment] 2023-11-02 08:40
> Thanks @bernhard-wunderbyte and @mwreichel! Now everyone will benefit. 😁

You're welcome 😁
