### ISSUE TITLE
Remove start time info when "No fixed time" 

### ISSUE THREAD

**Issue by cdipe** [jrchamp/moodle-mod_zoom#548] opened 2023-11-22 09:49 UTC
Start time is showing when having created a **Recurring meeting** with **No fixed time**
The start time showing is the default one hour ahead from when the meeting was created.

(Might be related to https://github.com/ncstate-delta/moodle-mod_zoom/issues/523 ?)

Using Moodle 4.1.6 and Zoom Meeting v5.1.0 2023082400

**Comment by cdipe** [comment] 2023-11-22 09:50
<img width="853" alt="image" src="https://github.com/ncstate-delta/moodle-mod_zoom/assets/14754240/e87e9bc6-7902-40ff-81b9-a532b9149e80">
<img width="802" alt="image" src="https://github.com/ncstate-delta/moodle-mod_zoom/assets/14754240/b23090ea-39ad-4a10-a6ea-31e598ef425a">

**Comment by jrchamp** [comment] 2023-11-30 16:23
Hi @cdipe!

This was fixed in [v5.1.1](https://github.com/ncstate-delta/moodle-mod_zoom/releases/tag/v5.1.1), though we recommend using the latest version which includes other bug fixes.

**Comment by jrchamp** [comment] 2023-11-30 16:24
Duplicate of #528

**Closed as not planned by jrchamp** 2023-11-30 16:24 UTC
Labels: bug

**Comment by cdipe** [comment] 2023-11-30 20:27
@jrchamp excellent, thank you!
