### ISSUE TITLE
XMLDB version should match the current plugin version

### ISSUE THREAD

**Issue by danielcifuentesopen** [jrchamp/moodle-mod_zoom#413] opened 2022-10-03 14:38 UTC
In the Zoom plugin, the version that appears in the zoom/db/install.xml file (VERSION="20210303") is different to the plugin version that appears in the zoom/version.php. These two should be the same.

**Comment by danmarsden** [comment] 2022-10-04 19:52
What makes you think they should be the same? They  mean different things and are different in core plugins too. The install.xml file will often have an old date(when the file was last changed) but version bumps due to lang changes, or other changes will be made many times increasing the core version number and do not touch tye xml file.

I'm not the zoom plugin maintainer but I would close this as not a bug.

**Comment by danmarsden** [comment] 2022-10-10 18:34
That doesn't occur in upstream or anywhere else. Usually the version numbers in those files are always different,  they mean different things.

**Comment by jrchamp** [comment] 2022-10-10 20:34
I took a look at the places I could think of and it seems like the original intent was to always update the `VERSION=` in the `install.xml` whenever the database changes. Here's a quick way to see all of the places where XMLDB bumps the internal version value which would later write out the updated value during export: https://github.com/moodle/moodle/search?p=1&q=setVersion+userdate

I agree that upstream seems to be inconsistent about when/if the VERSION value changes. This may be because the VERSION value seems to not be used for anything beyond displaying the current value in the XMLDB editor. I'll try and get some additional consensus.

**Comment by danmarsden** [comment] 2022-10-16 23:19
yes - that is correct - version in install.xml should be bumped when a change to the db structure occurs - this is what the xmldb editor does. (but not when naughty developers edit the xml file directly like I have been guilty of...)

But... the version in version.php is different - the version in version.php needs to be bumped when lang files change, when webservices added/removed, or when an upgrade.php step is required to modify content - none of these events require a change to the version stored in install.xml as these are different.

**Comment by jrchamp** [comment] 2022-10-17 19:14
Thank you @danielcifuentesopen and @danmarsden. We have indeed been guilty of not using the XMLDB Editor to make changes to the files it manages and for accepting Pull Requests that do the same. Going forward, we'll want to check that the install.xml's VERSION value is updated when that file changes (as an indication that the XMLDB Editor was used), but at no point will it match the version in version.php which has a different format (two additional digits) and purpose (as Dan M described).

**Closed as completed by jrchamp** 2022-10-17 19:14 UTC
